steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Pull previous evaluate image'
  entrypoint: 'bash'
  args: ['-c', 'docker pull europe-west4-docker.pkg.dev/mlopsdogclassification/mlops-dog-classification/dogs-evaluate:latest || exit 0']
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build evaluate image'
  env:
    - 'DOCKER_BUILDKIT=1'
  args: [
    'build',
    '.',
    '-t',
    'europe-west4-docker.pkg.dev/mlopsdogclassification/mlops-dog-classification/dogs-evaluate:latest',
    '--cache-from',
    'europe-west4-docker.pkg.dev/mlopsdogclassification/mlops-dog-classification/dogs-evaluate:latest',
    '--build-arg',
    'BUILDKIT_INLINE_CACHE=1',
    '-f',
    'dockerfiles/evaluate.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push evaluate image'
  args: [
    'push',
    'europe-west4-docker.pkg.dev/mlopsdogclassification/mlops-dog-classification/dogs-evaluate:latest'
  ]

options:
  logging: CLOUD_LOGGING_ONLY
