steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build bentoml image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west4-docker.pkg.dev/mlopsdogclassification/mlops-dog-classification/dogs-bentoml:latest',
    '-f',
    'dockerfiles/bentoml.dockerfile'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
