steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build evaluate image'
  env:
    - 'DOCKER_BUILDKIT=1'
  args: [
    'build',
    '.',
    '-t',
    'europe-west4-docker.pkg.dev/mlopsdogclassification/mlops-dog-classification/dogs-evaluate:latest',
    '-f',
    'dockerfiles/evaluate.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push evaluate image'
  args: [
    'push',
    'europe-west4-docker.pkg.dev/mlopsdogclassification/mlops-dog-classification/dogs-evaluate:latest'
  ]

options:
  logging: CLOUD_LOGGING_ONLY
