name: DVC Workflow

on:
  push:
    branches: [67-add-continuous-workflow-that-triggers-when-data-changes]
    paths:
    - '**/*.dvc'
    - '.dvc/**'

jobs:
  run_data_checker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h  # check remaining space

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --locked --dev

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Pull data
        run: |
          uv run dvc pull --no-run-cache

      - name: Check data statistics
        run: |
          uv run python -m dogs_classification.dataset_statistics > report.md

      - name: Post report as commit comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/commits/${{ github.sha }}/comments \
            --method POST \
            --field body="$(cat report.md)"
