name: DVC Workflow

on:
  push:
    branches: [67-add-continuous-workflow-that-triggers-when-data-changes]
    paths:
    - '**/*.dvc'
    - '.dvc/**'

jobs:
  run_data_checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --locked --dev
          uv tree

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Pull data
        run: |
          uv run dvc pull --no-run-cache

      - name: Check data statistics
        run: |
          uv run python -m dogs_classification.dataset_statistics > report.md

      - name: Post CML report
        uses: iterative/cml@v3
        with:
          command: comment create report.md
