name: Unit Tests

on:
 # push:
 #   branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: 3.13

      - name: Cache HuggingFace models
        uses: actions/cache@v6
        with:
          path: ~/.cache/huggingface
          key: hf-${{ runner.os }}-google-vit-base-patch16-224

      - name: Install dependencies
        run: |
          uv sync --locked --dev --extra train --extra serve

      - name: Auth with GCP
        if: github.actor != 'dependabot[bot]'
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Start BentoML service
        if: github.actor != 'dependabot[bot]'
        shell: bash
        run: |
          uv run bentoml serve src.dogs_classification.bentoml:DogBreedClassificationService &


      - name: Wait for BentoML
        if: github.actor != 'dependabot[bot]'
        shell: bash
        run: |
          for i in {1..150}; do
            if curl -fs http://localhost:3000/livez; then
              echo "BentoML is ready"
              exit 0
            fi
            sleep 2
          done

          echo "BentoML did not become ready after 5 minutes"
          exit 1

      - name: Run tests
        env:
          BENTOML_URL: http://localhost:3000
          HAS_GCP: ${{ github.actor != 'dependabot[bot]' }}
        run: |
          if [ "$HAS_GCP" = "true" ]; then
            uv run coverage run -m pytest tests/ -v --ignore=tests/performancetests
          else
            uv run coverage run -m pytest tests/ -v --ignore=tests/performancetests --ignore=tests/test_bentoml.py
          fi
