name: Unit Tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: 3.13

      - name: Install dependencies
        run: |
          uv sync --locked --dev

      - name: Cache model
        id: cache-model
        uses: actions/cache@v4
        with:
          path: models/best_model.pt
          key: model-${{ hashFiles('models/best_model.pt.dvc') }}

      - name: Authenticate to GCS
        if: steps.cache-model.outputs.cache-hit != 'true'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Pull model with DVC
        if: steps.cache-model.outputs.cache-hit != 'true'
        run: uv run dvc pull models/best_model.pt

      - name: Run tests
        run: |
          uv run coverage run -m pytest tests/
