name: Test performance tests
on:
  pull_request:
    branches: [master, main]

jobs:
  test_model:
    runs-on: ubuntu-latest
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Auth with GCP
      uses: google-github-actions/auth@v3
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Install dependencies
      run: |
        uv sync --locked --dev --extra train --extra cloud

    - name: Pull dataset with DVC
      run: |
        uv run dvc pull -r remote_storage --force

    - name: Run performance tests
      run: |
        uv run pytest tests/performancetests/test_model.py
